version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3310:3306

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: database

volumes:
  database:
